### ISSUE TITLE
variable names in hdf5

### ISSUE THREAD

**Issue by erasmuss** [raman-noodles/raman-spectra-decomp-analysis#15]
Currently the hdf5 file calls the x-axis/y-axis columns from the excel (.csv) as 'x' and 'y' but they should be properly named as (for x) 'wavelength' and (for y) 'counts'

Think this is under @ParkerSteichen realm, but also not sure how much it impacts @kernb2 

Note: Sometimes the y is also called 'intensity' or 'arb. units' in literature because the counts / amount of resonance that the raman probe and cell emitted can be a function of the set up.

**Comment by ParkerSteichen** [comment]
I updated this in the the .py to make it more clear when reading the code directly. I don't believe those variable names actually got saved to the hdf5 and were just internal to the function but it never hurts to make the code more clear.
