### ISSUE TITLE
add function to dataprep that adds all data files in a directory to a hdf5 file

### ISSUE THREAD

**Issue by ParkerSteichen** [raman-noodles/raman-spectra-decomp-analysis#17]

**Comment by erasmuss** [comment]
done, function is `dataimport.py`

**Comment by erasmuss** [comment]
going to merge the alone module `dataimport.py` to be within the `dataprep.py` module after team discussion.

**Comment by erasmuss** [comment]
completed by me with dataimport.py file function.
