### ISSUE TITLE
interpolatespectra.interp_and_norm function Failed Test

### ISSUE THREAD

**Issue by kernb2** [raman-noodles/raman-spectra-decomp-analysis#53]
FAIL: A function that tests that the interpolatespectra.interp_and_norm function is behaving
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/raman-noodles/raman-spectra-decomp-analysis/ramandecompy/tests/test_interpolatespectra.py", line 32, in test_interp_and_norm
    assert isinstance(tuple_list[0][0], np.int32), 'first element of tuple is not a np.int64'
AssertionError: first element of tuple is not a np.int64

**Comment by erasmuss** [comment]
This should be a quick type fix. 
Below is text from: https://github.com/numpy/numpy/issues/2951
> This is correct -- python 'int' is either 32 or 64 bit (depending on your
> build; you're using a 32-bit python), so either np.int32 or np.int64
> derives from it. np.float32 isn't an instance of 'float', either, because
> similarly Python 'float' is specifically stored in double-precision.
> 
> (Really even this is silly because numpy ints aren't instances of 'int'
> or 'float', but whatever.)
> 
> isinstance(..., int) is the wrong tool for what you're trying to do. If you
> want to detect integers in general using numpy types, the simplest thing to
> do is isinstance(..., np.integer).

also here is another link: https://stackoverflow.com/questions/40429917/in-python-how-would-you-check-if-a-number-is-one-of-the-integer-types

**Comment by erasmuss** [comment]
updated. the bug should be crushed now.
