### ISSUE TITLE
molardecomp example use of exp key list instead of keylist

### ISSUE THREAD

**Issue by kernb2** [raman-noodles/raman-spectra-decomp-analysis#55]
Need to update key_list to exp_key_list in the molardecomp example

Example:

#making a loop to identify peaks in all experimental data set and add label to them
frames = []
for i, key in enumerate(exp_key_list):
    df = peakidentify.peak_assignment(hdf5_expfilename, key, hdf5_calfilename, 10)
    frames.append(df)

**Comment by erasmuss** [comment]
Will deep dive tomorrow and discuss then. thanks for pointing this out!

**Comment by erasmuss** [comment]
deleted and updated file. this bug is crushed
