### ISSUE TITLE
unnecesary dataframe & syntax error 

### ISSUE THREAD

**Issue by kernb2** [raman-noodles/raman-spectra-decomp-analysis#56]
just comment out the unnecessary stuff
Right before Step 6
area_f = []
# area_f_db = pd.DataFrame =( columns = 'ratioAUC')
for index, row in area_base.iterrows():
    AUCratio = area_base.auc[index]/area_base.cal_auc[index]
    area_f.append((area_base.exp_cond[index], AUCratio))
    print("experimental conditions %s with ratio AUC is %s" % (area_base.exp_cond[index], AUCratio))

    
    
# area_base.append()

**Comment by erasmuss** [comment]
@kernb2 is uploading to a seprate branch to be moved to elizabeth

**Comment by erasmuss** [comment]
This issue was fixed along with the same time as issue #55 so this bug is crushed
